export const HU_GUIDE_ROUTES = Object.freeze({
  hub: "/hu/utmutatok/",
  battery: "/hu/utmutatok/lakoauto-akkumulator-kapacitas/",
  solar: "/hu/utmutatok/hany-watt-napelem-lakoautohoz/",
  mppt: "/hu/utmutatok/mppt-szabalyozo-kivalasztasa/",
});

const guides = Object.freeze({
  battery: {
    title: "Hány Ah akkumulátor kell a lakóautóba? Számítás és példa",
    description: "Számítsd ki a lakóautó szükséges akkumulátorkapacitását a napi energiafogyasztásból. Képlet, AGM–LiFePO₄ különbség és 12 V-os példa.",
    kicker: "Gyakorlati számítás",
    heading: "Hány Ah akkumulátorra van szükséged?",
    lead: "A helyes válasz nem a gyakran emlegetett 100 Ah értékkel kezdődik, hanem azzal, hogy naponta ténylegesen hány wattórát fogyasztasz.",
    reading: "8 perc olvasás",
    toc: [["fogyasztas","Napi fogyasztás"],["keplet","Kapacitás számítása"],["ah-wh","Ah és Wh"],["tartalek","Tartalék"],["hibak","Gyakori hibák"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Add össze a napi fogyasztást Wh-ban, szorozd meg a töltés nélküli napok számával és a tartalékkal, majd oszd el a használható kapacitásrész és a rendszerfeszültség szorzatával. Napi 600 Wh és két nap esetén a konzervatív modell körülbelül 144 Ah LiFePO₄ vagy 230 Ah AGM kapacitást ad 12 V-on.</div>
<h2 id="fogyasztas">1. Számítsd ki a napi fogyasztást</h2><p>Minden készüléknél szorozd össze a wattban megadott teljesítményt, a napi üzemidőt és a darabszámot. Az eredmény a napi wattóra.</p><div class="formula">Napi fogyasztás (Wh) = teljesítmény (W) × üzemidő (h) × darabszám</div>
<table><thead><tr><th>Készülék</th><th>Példa</th><th>Fogyasztás</th></tr></thead><tbody><tr><td>Kompresszoros hűtő</td><td>átlagosan 20 W × 24 h</td><td>480 Wh</td></tr><tr><td>LED-világítás</td><td>12 W × 4 h</td><td>48 Wh</td></tr><tr><td>Laptop</td><td>45 W × 2 h</td><td>90 Wh</td></tr><tr><th>Összesen</th><th></th><th>618 Wh/nap</th></tr></tbody></table><p>Ez tervezési példa, nem univerzális fogyasztási adat. Használd a készülék adattábláját vagy saját mérésedet.</p>
<h2 id="keplet">2. Váltsd át a Wh-t akkumulátorkapacitásra</h2><div class="formula">Kapacitás (Ah) = Wh × napok × 1,15 ÷ használható rész ÷ feszültség</div><p>A MyPowerSetup 15% tervezési tartalékot használ. LiFePO₄ esetén 80%, AGM/ólomakkumulátornál 50% használható kapacitással számol. A konkrét akkumulátor és BMS korlátait mindig ellenőrizni kell.</p><div class="example"><strong>Példa: napi 600 Wh, két nap, 12 V</strong><p>LiFePO₄: 600 × 2 × 1,15 ÷ 0,80 ÷ 12 = <strong>144 Ah</strong>.</p><p>AGM: 600 × 2 × 1,15 ÷ 0,50 ÷ 12 = <strong>230 Ah</strong>.</p></div>
<h2 id="ah-wh">Az Ah feszültség nélkül nem mondja meg az energiát</h2><p>100 Ah 12 V-on körülbelül 1200 Wh névleges energia, 24 V-on viszont 2400 Wh. Ezért a rendszereket Wh-ban hasonlítsd össze, vagy mindig add meg a feszültséget.</p><div class="formula">Névleges energia (Wh) = kapacitás (Ah) × feszültség (V)</div>
<h2 id="tartalek">Mekkora tartalék indokolt?</h2><ul><li><strong>Hétvégi használat és rendszeres töltés:</strong> kisebb tartalék is elég lehet, ha ismered a fogyasztást.</li><li><strong>Hűtő és fontos fogyasztók:</strong> számolj a hőséggel, rosszabb hatásfokkal és nap nélküli időszakokkal.</li><li><strong>Téli használat:</strong> ellenőrizd a lítiumakkumulátor alacsony hőmérsékletű töltési korlátját.</li><li><strong>230 V-os fogyasztók:</strong> vedd figyelembe az inverter veszteségét és saját fogyasztását.</li></ul><div class="note"><strong>Fontos:</strong> a kapacitás önmagában nem bizonyítja, hogy az akkumulátor elviseli a nagy terhelést. Ellenőrizd a BMS maximális áramát, a vezetékeket, biztosítékokat, invertert és töltőforrásokat.</div>
${calculatorCta("Számítsd ki a teljes rendszeredet")}
<h2 id="hibak">Gyakori hibák</h2><ol><li>Más járművének akkumulátora alapján választani.</li><li>Az Ah értékeket feszültség nélkül összehasonlítani.</li><li>Minden kémiánál 100% használható kapacitást feltételezni.</li><li>Kihagyni a veszteségeket, tartalékot és a nap nélküli időszakokat.</li><li>Lítiumra váltáskor nem ellenőrizni a töltőket.</li></ol><p>Az energiaigényből induló méretezés alapját a <a href="https://www.renogy.com/blogs/learn-center/battery-sizing-guide" rel="nofollow noopener">Renogy akkumulátorméretezési útmutatója</a> is bemutatja. A megengedett kisütési mélységet mindig a konkrét akkumulátor adatlapja határozza meg.</p>`,
  },
  solar: {
    title: "Hány watt napelem kell a lakóautóra? Számítás",
    description: "Számítsd ki a lakóautó napelemes teljesítményét a fogyasztás, évszak és veszteségek alapján. Képlet, példa és MPPT-ellenőrzés.",
    kicker: "Gyakorlati számítás",
    heading: "Hány watt napelemre van szükséged?",
    lead: "A panelteljesítményt nem a jármű mérete, hanem a napi fogyasztás, az évszak, az árnyék és a rendszer tényleges veszteségei határozzák meg.",
    reading: "8 perc olvasás",
    toc: [["keplet","Wp számítása"],["evszak","Évszak"],["akkumulator","Akkumulátor"],["mppt","MPPT"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Napi 600 Wh fogyasztás, négy teljes napsütéses óra és 75%-os rendszerhatásfok mellett körülbelül 200 Wp szükséges. 15% tartalékkal az eredmény 230 Wp. Tavasszal, ősszel, télen vagy árnyékban ennél jóval nagyobb teljesítmény kellhet.</div>
<h2 id="keplet">A panelteljesítmény alapképlete</h2><div class="formula">Napelem (Wp) = napi Wh × 1,15 ÷ teljes napsütéses órák ÷ 0,75</div><div class="example"><strong>Példa: napi 600 Wh nyáron</strong><p>600 × 1,15 ÷ 4 ÷ 0,75 = <strong>230 Wp</strong>. A gyakorlatban 240–300 Wp lehet célszerű a tetőhely és a kívánt tartalék szerint.</p></div>
<h2 id="evszak">Miért nem működik egyetlen érték egész évben?</h2><table><thead><tr><th>Körülmény</th><th>Hatás</th></tr></thead><tbody><tr><td>Alacsony napállás és rövid nappal</td><td>Sokkal kevesebb napi energia</td></tr><tr><td>Részleges árnyék</td><td>Egy panelt vagy a teljes soros ágat korlátozhatja</td></tr><tr><td>Vízszintes panel</td><td>Nyáron kívül kedvezőtlenebb szög</td></tr><tr><td>Magas panelhőmérséklet</td><td>Alacsonyabb pillanatnyi teljesítmény</td></tr><tr><td>Szabályozó- és kábelveszteség</td><td>Kevesebb energia jut az akkumulátorba</td></tr></tbody></table><p>A kalkulátor nyáron 4,5, tavasszal és ősszel 3, télen 1,5 teljes napsütéses órával számol. Ez konzervatív tervezési feltételezés, nem helyi időjárás-előrejelzés.</p>
<h2 id="akkumulator">A napelem nem helyettesíti a megfelelő akkumulátort</h2><p>A napelem csak megfelelő fényben termel. Az akkumulátornak kell áthidalnia az éjszakát, az árnyékot és a rossz időt. A fogyasztást, autonómiát, akkumulátort, panelt és az alternátoros vagy hálózati töltést együtt méretezd.</p>
<h2 id="mppt">Ellenőrizd az MPPT-szabályozót</h2><p>Nem csak a töltőáramot kell ellenőrizni: számít a maximális PV-feszültség, az Isc és a megengedett panelteljesítmény is. Soros kapcsolásnál a feszültségek összeadódnak, a Voc pedig hidegben nő. A határértékeket a gyártói kézikönyvben, például a <a href="https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_75-10_up_to_100-20/en/index-en.html" rel="nofollow noopener">Victron SmartSolar MPPT kézikönyvében</a> kell ellenőrizni.</p><div class="note"><strong>Biztonság:</strong> a járműre szerelés megfelelő rögzítést, tetőátvezetést, leválasztást, védelmet és vezetékezést igényel. A kalkulátor nem villamos terv.</div>${calculatorCta("Számítsd ki a szükséges panelteljesítményt")}`,
  },
  mppt: {
    title: "Hogyan válassz MPPT-szabályozót napelemhez?",
    description: "MPPT-szabályozó választása 12 vagy 24 V-os rendszerhez: töltőáram, Voc, Isc, panelteljesítmény és akkumulátorprofil ellenőrzése.",
    kicker: "Rendszerillesztés",
    heading: "Hogyan válassz MPPT-szabályozót?",
    lead: "A 100/30 jelölés nem egyszerű teljesítményosztály: az első érték a paneloldali feszültséghatárt, a második a maximális töltőáramot jelöli.",
    reading: "9 perc olvasás",
    toc: [["aram","Töltőáram"],["feszultseg","Voc"],["ellenorzes","Öt paraméter"],["pelda","Példa"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>A szabályozónak egyszerre kell megfelelnie az akkumulátorfeszültségnek, a panelek hidegben várható maximális Voc értékének, a rövidzárási áramnak, a névleges panelteljesítménynek és a szükséges töltőáramnak. Egyetlen adat ellenőrzése nem elég.</div>
<h2 id="aram">1. A töltőáram első becslése</h2><div class="formula">Szabályozó árama (A) ≈ panelteljesítmény (W) ÷ akkumulátorfeszültség (V) × 1,25</div><p>400 Wp és 12 V esetén: 400 ÷ 12 × 1,25 ≈ <strong>42 A</strong>. Ez konzervatív első szűrő; az eredményt hasonlítsd össze a gyártó megengedett PV-teljesítmény táblázatával.</p><table><thead><tr><th>Napelem</th><th>Rendszer</th><th>Áram 25% tartalékkal</th></tr></thead><tbody><tr><td>200 Wp</td><td>12 V</td><td>21 A</td></tr><tr><td>400 Wp</td><td>12 V</td><td>42 A</td></tr><tr><td>400 Wp</td><td>24 V</td><td>21 A</td></tr></tbody></table>
<h2 id="feszultseg">2. Ellenőrizd a Voc értéket a legalacsonyabb hőmérsékleten</h2><p>Soros kapcsolásnál a panel-feszültségek összeadódnak, az üresjárati feszültség pedig hidegben nő. A hőmérséklettel korrigált összes Voc értéknek a gyártó által előírt tartalékkal a szabályozó abszolút határa alatt kell maradnia.</p><div class="note"><strong>Példa a 100/30 jelölésre:</strong> a dokumentáció 100 V maximális Voc és 30 A töltőáram határt adhat meg. Ettől még külön ellenőrizni kell az Isc értéket és a megengedett PV-teljesítményt.</div>
<h2 id="ellenorzes">3. Öt paraméternek kell egyszerre megfelelnie</h2><ol><li><strong>Akkumulátorfeszültség:</strong> 12, 24 vagy 48 V a rendszer szerint.</li><li><strong>Maximális PV Voc:</strong> a legalacsonyabb hőmérsékletre korrigálva.</li><li><strong>Rövidzárási áram, Isc:</strong> a párhuzamos ágakkal és a szükséges tartalékkal.</li><li><strong>Megengedett PV-teljesítmény:</strong> az akkumulátorfeszültségtől függően.</li><li><strong>Töltési profil:</strong> a konkrét AGM- vagy LiFePO₄-akkumulátorhoz illesztve.</li></ol>
<h2 id="pelda">Példa egy adatlapból</h2><p>A Victron SmartSolar 100/20 <a href="https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_75-10_up_to_100-20/en/technical-specifications.html" rel="nofollow noopener">műszaki specifikációja</a> 20 A akkumulátoráramot, 100 V maximális Voc értéket, valamint 12 V-on 290 W, 24 V-on 580 W PV-teljesítményt ad meg. Ugyanaz a szabályozó tehát magasabb akkumulátorfeszültségnél nagyobb panelteljesítményt fogadhat. Ez a szabály magyarázata, nem termékajánlás.</p>${calculatorCta("Számítsd ki az MPPT-t a teljes rendszerrel")}`,
  },
});

export function renderHungarianGuide(kind) {
  if (kind === "hub") return renderHub();
  const guide = guides[kind];
  if (!guide || !HU_GUIDE_ROUTES[kind]) throw new Error(`HU_GUIDE_UNKNOWN:${kind}`);
  const route = HU_GUIDE_ROUTES[kind];
  const schema = JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:guide.heading, inLanguage:"hu-HU", author:{ "@type":"Person", name:"Petr Gálík", url:"https://mypowersetup.com/hu/a-projektrol/" }, mainEntityOfPage:`https://mypowersetup.com${route}` });
  return `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${guide.title}</title><meta name="description" content="${guide.description}"><meta property="og:title" content="${guide.title}"><meta property="og:description" content="${guide.description}"><meta property="og:type" content="article"><meta property="og:url" content="https://mypowersetup.com${route}"><meta property="og:locale" content="hu_HU"><meta property="og:image" content="https://mypowersetup.com/social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/article.css"><script type="application/ld+json">${schema}</script></head><body>${header()}<section class="article-hero"><div class="article-hero-inner"><div class="crumbs"><a href="/hu/">Kezdőlap</a> › <a href="${HU_GUIDE_ROUTES.hub}">Útmutatók</a></div><span class="kicker">${guide.kicker}</span><h1>${guide.heading}</h1><p>${guide.lead}</p><div class="article-meta"><span>Szerző: <a href="/hu/a-projektrol/">Petr Gálík</a></span><span>Frissítve: 2026. 08. 28.</span><span>${guide.reading}</span><span>Átlátható módszertan</span></div></div></section><main class="article-layout"><article class="article">${guide.body}${safety()}</article><aside class="toc"><strong>Az útmutatóban</strong>${guide.toc.map(([id,label])=>`<a href="#${id}">${label}</a>`).join("")}</aside></main>${related(kind)}${footer()}</body></html>`;
}

function renderHub() {
  const cards = [["battery","Akkumulátorkapacitás","A napi fogyasztástól a szükséges Ah értékig."],["solar","Napelem méretezése","Évszak, veszteségek és szükséges Wp."],["mppt","MPPT kiválasztása","Áram, Voc, Isc és PV-teljesítmény együtt."]];
  return `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Lakóautó elektromos rendszer útmutatók | MyPowerSetup</title><meta name="description" content="Gyakorlati útmutatók akkumulátor, napelem és MPPT méretezéséhez, ugyanazzal a módszertannal, amelyet a MyPowerSetup kalkulátor használ."><link rel="stylesheet" href="/article.css"></head><body>${header()}<section class="article-hero"><div class="article-hero-inner"><span class="kicker">Tudásbázis</span><h1>Érthető lakóautó-elektromosság</h1><p>A képletektől a biztonsági korlátokig: minden útmutató ugyanazt az ellenőrzött számítási modellt használja, mint a kalkulátor.</p></div></section><main class="article-layout" style="grid-template-columns:1fr"><article class="article"><div class="related-grid">${cards.map(([kind,title,text])=>`<a href="${HU_GUIDE_ROUTES[kind]}"><strong>${title}</strong><br><span>${text}</span></a>`).join("")}</div>${calculatorCta("Kezdd a saját fogyasztásoddal")}${safety()}</article></main>${footer()}</body></html>`;
}

function header() { return `<header class="article-header"><a class="article-brand" href="/hu/">⚡ MyPowerSetup</a><nav><a href="${HU_GUIDE_ROUTES.hub}">Útmutatók</a><a href="/hu/#kalkulator">Kalkulátor</a></nav></header>`; }
function calculatorCta(title) { return `<section class="cta"><h2>${title}</h2><p>Válaszd ki a fogyasztókat, az üzemidőt, az évszakot és a kívánt autonómiát.</p><a href="/hu/#kalkulator">Saját rendszer kiszámítása →</a></section>`; }
function safety() { return `<div class="sources"><h2>Források, módszertan és biztonság</h2><p>A képletek a <a href="/hu/modszertan/">nyilvános módszertanban</a> szereplő konzervatív tervezési feltételeket követik. A termékadatlap és a gyártói kézikönyv mindig elsőbbséget élvez. Az eredmény tájékoztató méretezés, nem villamos terv; a vezetékezést, védelmeket és szerelést megfelelő képesítésű szakembernek kell ellenőriznie.</p></div>`; }
function related(kind) { const links = kind === "battery" ? [["solar","Napelem méretezése"]] : kind === "solar" ? [["mppt","MPPT kiválasztása"],["battery","Akkumulátorkapacitás"]] : [["solar","Napelem méretezése"],["battery","Akkumulátorkapacitás"]]; return `<section class="related"><h2>Olvass tovább</h2><div class="related-grid">${links.map(([target,label])=>`<a href="${HU_GUIDE_ROUTES[target]}">${label} →</a>`).join("")}</div></section>`; }
function footer() { return `<footer class="article-footer">A számítás tájékoztató jellegű, nem villamos terv. A konkrét telepítést és védelmeket szakemberrel ellenőriztesd.</footer><script type="module" src="/src/analytics.js"></script>`; }
