export const HU_GUIDE_ROUTES = Object.freeze({
  hub: "/hu/utmutatok/",
  battery: "/hu/utmutatok/lakoauto-akkumulator-kapacitas/",
  solar: "/hu/utmutatok/hany-watt-napelem-lakoautohoz/",
  mppt: "/hu/utmutatok/mppt-szabalyozo-kivalasztasa/",
  inverter: "/hu/utmutatok/lakoauto-inverter-kivalasztasa/",
  dcDc: "/hu/utmutatok/dc-dc-tolto-kivalasztasa/",
  shore: "/hu/utmutatok/230-v-os-tolto-kivalasztasa/",
});

const guides = Object.freeze({
  battery: {
    title: "Hány Ah akkumulátor kell a lakóautóba? Számítás és példa",
    description: "Számítsd ki a lakóautó szükséges akkumulátorkapacitását a napi energiafogyasztásból. Képlet, AGM–LiFePO₄ különbség és 12 V-os példa.",
    kicker: "Gyakorlati számítás",
    heading: "Hány Ah akkumulátorra van szükséged?",
    lead: "A helyes válasz nem a gyakran emlegetett 100 Ah értékkel kezdődik, hanem azzal, hogy naponta ténylegesen hány wattórát fogyasztasz.",
    reading: "8 perc olvasás",
    toc: [["fogyasztas","Napi fogyasztás"],["keplet","Kapacitás számítása"],["magyar-peldak","Magyar példák"],["ah-wh","Ah és Wh"],["tartalek","Tartalék"],["hibak","Gyakori hibák"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Add össze a napi fogyasztást Wh-ban, szorozd meg a töltés nélküli napok számával és a tartalékkal, majd oszd el a használható kapacitásrész és a rendszerfeszültség szorzatával. Napi 600 Wh és két nap esetén a konzervatív modell körülbelül 144 Ah LiFePO₄ vagy 230 Ah AGM kapacitást ad 12 V-on.</div>
<h2 id="fogyasztas">1. Számítsd ki a napi fogyasztást</h2><p>Minden készüléknél szorozd össze a wattban megadott teljesítményt, a napi üzemidőt és a darabszámot. Az eredmény a napi wattóra.</p><div class="formula">Napi fogyasztás (Wh) = teljesítmény (W) × üzemidő (h) × darabszám</div>
<table><thead><tr><th>Készülék</th><th>Példa</th><th>Fogyasztás</th></tr></thead><tbody><tr><td>Kompresszoros hűtő</td><td>átlagosan 20 W × 24 h</td><td>480 Wh</td></tr><tr><td>LED-világítás</td><td>12 W × 4 h</td><td>48 Wh</td></tr><tr><td>Laptop</td><td>45 W × 2 h</td><td>90 Wh</td></tr><tr><th>Összesen</th><th></th><th>618 Wh/nap</th></tr></tbody></table><p>Ez tervezési példa, nem univerzális fogyasztási adat. Használd a készülék adattábláját vagy saját mérésedet.</p>
<h2 id="keplet">2. Váltsd át a Wh-t akkumulátorkapacitásra</h2><div class="formula">Kapacitás (Ah) = Wh × napok × 1,15 ÷ használható rész ÷ feszültség</div><p>A MyPowerSetup 15% tervezési tartalékot használ. LiFePO₄ esetén 80%, AGM/ólomakkumulátornál 50% használható kapacitással számol. A konkrét akkumulátor és BMS korlátait mindig ellenőrizni kell.</p><div class="example"><strong>Példa: napi 600 Wh, két nap, 12 V</strong><p>LiFePO₄: 600 × 2 × 1,15 ÷ 0,80 ÷ 12 = <strong>144 Ah</strong>.</p><p>AGM: 600 × 2 × 1,15 ÷ 0,50 ÷ 12 = <strong>230 Ah</strong>.</p></div>
<h2 id="magyar-peldak">Két magyarországi használati példa</h2><div class="example"><strong>Két forró nap a Balatonnál</strong><p>A kompresszoros hűtő nagyobb terhelése napi 700 Wh-ra emelheti a fogyasztást. Két napra 700 × 2 × 1,15 ÷ 0,80 ÷ 12 = <strong>168 Ah LiFePO₄</strong>, ezért a gyakorlatban legalább 170–200 Ah és a BMS terhelhetőségének ellenőrzése indokolt.</p></div><div class="example"><strong>Termálkemping rendszeres 230 V-os csatlakozással</strong><p>Napi 500 Wh és egy nap tartalék mellett 60 Ah LiFePO₄ a számított minimum. A gyakorlatban 60–100 Ah megfelelő lehet, ha a 230 V-os töltő profilja, árama és a kemping csatlakozásának terhelése is megfelelő. A ritka hálózati töltéshez nagyobb autonómia kell.</p></div><p>Egy meglévő 100 Ah LiFePO₄ akkumulátor körülbelül 960 Wh tervezetten használható energiát ad 12 V-on. Ha ez kevés, előbb döntsd el, hogy a kapacitás, a BMS árama vagy a napi visszatöltés a szűk keresztmetszet; ettől függ a legkisebb értelmes fejlesztés.</p>
<h2 id="ah-wh">Az Ah feszültség nélkül nem mondja meg az energiát</h2><p>100 Ah 12 V-on körülbelül 1200 Wh névleges energia, 24 V-on viszont 2400 Wh. Ezért a rendszereket Wh-ban hasonlítsd össze, vagy mindig add meg a feszültséget.</p><div class="formula">Névleges energia (Wh) = kapacitás (Ah) × feszültség (V)</div>
<h2 id="tartalek">Mekkora tartalék indokolt?</h2><ul><li><strong>Hétvégi használat és rendszeres töltés:</strong> kisebb tartalék is elég lehet, ha ismered a fogyasztást.</li><li><strong>Hűtő és fontos fogyasztók:</strong> számolj a hőséggel, rosszabb hatásfokkal és nap nélküli időszakokkal.</li><li><strong>Téli használat:</strong> ellenőrizd a lítiumakkumulátor alacsony hőmérsékletű töltési korlátját.</li><li><strong>230 V-os fogyasztók:</strong> vedd figyelembe az inverter veszteségét és saját fogyasztását.</li></ul><div class="note"><strong>Fontos:</strong> a kapacitás önmagában nem bizonyítja, hogy az akkumulátor elviseli a nagy terhelést. Ellenőrizd a BMS maximális áramát, a vezetékeket, biztosítékokat, invertert és töltőforrásokat.</div>
${calculatorCta("Számítsd ki a teljes rendszeredet")}
<h2 id="hibak">Gyakori hibák</h2><ol><li>Más járművének akkumulátora alapján választani.</li><li>Az Ah értékeket feszültség nélkül összehasonlítani.</li><li>Minden kémiánál 100% használható kapacitást feltételezni.</li><li>Kihagyni a veszteségeket, tartalékot és a nap nélküli időszakokat.</li><li>Lítiumra váltáskor nem ellenőrizni a töltőket.</li></ol><p>Az energiaigényből induló méretezés alapját a <a href="https://www.renogy.com/blogs/learn-center/battery-sizing-guide" rel="nofollow noopener">Renogy akkumulátorméretezési útmutatója</a> is bemutatja. A megengedett kisütési mélységet mindig a konkrét akkumulátor adatlapja határozza meg.</p>`,
  },
  solar: {
    title: "Hány watt napelem kell a lakóautóra? Számítás",
    description: "Számítsd ki a lakóautó napelemes teljesítményét a fogyasztás, évszak és veszteségek alapján. Képlet, példa és MPPT-ellenőrzés.",
    kicker: "Gyakorlati számítás",
    heading: "Hány watt napelemre van szükséged?",
    lead: "A panelteljesítményt nem a jármű mérete, hanem a napi fogyasztás, az évszak, az árnyék és a rendszer tényleges veszteségei határozzák meg.",
    reading: "8 perc olvasás",
    toc: [["keplet","Wp számítása"],["evszak","Évszak"],["helyi-peldak","Magyar példák"],["akkumulator","Akkumulátor"],["mppt","MPPT"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Napi 600 Wh fogyasztás, 15% tartalék, 4,5 teljes napsütéses óra és 75%-os rendszerhatásfok mellett 205 Wp szükséges. A gyakorlatban legalább 220–250 Wp célszerű; tavasszal, ősszel, télen vagy árnyékban ennél jóval nagyobb teljesítmény kellhet.</div>
<h2 id="keplet">A panelteljesítmény alapképlete</h2><div class="formula">Napelem (Wp) = napi Wh × 1,15 ÷ teljes napsütéses órák ÷ 0,75</div><div class="example"><strong>Példa: napi 600 Wh nyáron</strong><p>600 × 1,15 ÷ 4,5 ÷ 0,75 = <strong>205 Wp</strong>. A gyakorlatban 220–250 Wp lehet célszerű a tetőhely és a kívánt tartalék szerint.</p></div>
<h2 id="evszak">Miért nem működik egyetlen érték egész évben?</h2><table><thead><tr><th>Körülmény</th><th>Hatás</th></tr></thead><tbody><tr><td>Alacsony napállás és rövid nappal</td><td>Sokkal kevesebb napi energia</td></tr><tr><td>Részleges árnyék</td><td>Egy panelt vagy a teljes soros ágat korlátozhatja</td></tr><tr><td>Vízszintes panel</td><td>Nyáron kívül kedvezőtlenebb szög</td></tr><tr><td>Magas panelhőmérséklet</td><td>Alacsonyabb pillanatnyi teljesítmény</td></tr><tr><td>Szabályozó- és kábelveszteség</td><td>Kevesebb energia jut az akkumulátorba</td></tr></tbody></table><p>A kalkulátor nyáron 4,5, tavasszal és ősszel 3, télen 1,5 teljes napsütéses órával számol. Ez konzervatív tervezési feltételezés, nem helyi időjárás-előrejelzés.</p>
<h2 id="helyi-peldak">Két magyarországi használati példa</h2><div class="example"><strong>Nyári hétvége a Balatonnál</strong><p>Napi 500 Wh fogyasztás és 4,5 nyári teljes napsütéses óra mellett 500 × 1,15 ÷ 4,5 ÷ 0,75 = <strong>171 Wp</strong>, ezért a gyakorlatban legalább 200 Wp indokolt. A felmelegedett panel és a hűtő nagyobb fogyasztása gyorsan felhasználhatja a tartalékot.</p></div><div class="example"><strong>Tavaszi utazás a hegyvidéken</strong><p>Napi 650 Wh és 3 teljes napsütéses óra mellett <strong>333 Wp</strong> szükséges, ezért 350–400 Wp vagy kisebb napelem és DC–DC töltés kombinációja reálisabb. A domborzat és a közeli fák a tiszta nap egy részét is levághatják.</p></div><p>Az adott hely és hónap ellenőrzéséhez használd az Európai Bizottság ingyenes <a href="https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en" rel="nofollow noopener">PVGIS eszközét</a>. A helyi horizontot figyelembe tudja venni, a közeli fák vagy épületek árnyékát azonban nem; az eredményt vízszintes járműpanelre és rendszer-veszteségekre is korrigálni kell.</p>
<h2 id="akkumulator">A napelem nem helyettesíti a megfelelő akkumulátort</h2><p>A napelem csak megfelelő fényben termel. Az akkumulátornak kell áthidalnia az éjszakát, az árnyékot és a rossz időt. A fogyasztást, autonómiát, akkumulátort, panelt és az alternátoros vagy hálózati töltést együtt méretezd.</p>
<h2 id="mppt">Ellenőrizd az MPPT-szabályozót</h2><p>Nem csak a töltőáramot kell ellenőrizni: számít a maximális PV-feszültség, az Isc és a megengedett panelteljesítmény is. Soros kapcsolásnál a feszültségek összeadódnak, a Voc pedig hidegben nő. A határértékeket a gyártói kézikönyvben, például a <a href="https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_75-10_up_to_100-20/en/index-en.html" rel="nofollow noopener">Victron SmartSolar MPPT kézikönyvében</a> kell ellenőrizni.</p><div class="note"><strong>Biztonság:</strong> a járműre szerelés megfelelő rögzítést, tetőátvezetést, leválasztást, védelmet és vezetékezést igényel. A kalkulátor nem villamos terv.</div>${calculatorCta("Számítsd ki a szükséges panelteljesítményt")}`,
  },
  mppt: {
    title: "Hogyan válassz MPPT-szabályozót napelemhez?",
    description: "MPPT-szabályozó választása 12 vagy 24 V-os rendszerhez: töltőáram, Voc, Isc, panelteljesítmény és akkumulátorprofil ellenőrzése.",
    kicker: "Rendszerillesztés",
    heading: "Hogyan válassz MPPT-szabályozót?",
    lead: "A 100/30 jelölés nem egyszerű teljesítményosztály: az első érték a paneloldali feszültséghatárt, a második a maximális töltőáramot jelöli.",
    reading: "9 perc olvasás",
    toc: [["aram","Töltőáram"],["feszultseg","Voc"],["ellenorzes","Öt paraméter"],["pelda","Példa"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>A szabályozónak egyszerre kell megfelelnie az akkumulátorfeszültségnek, a panelek hidegben várható maximális Voc értékének, a rövidzárási áramnak, a névleges panelteljesítménynek és a szükséges töltőáramnak. Egyetlen adat ellenőrzése nem elég.</div>
<h2 id="aram">1. A töltőáram első becslése</h2><div class="formula">Szabályozó árama (A) ≈ panelteljesítmény (W) ÷ akkumulátorfeszültség (V) × 1,25</div><p>400 Wp és 12 V esetén: 400 ÷ 12 × 1,25 ≈ <strong>42 A</strong>. Ez konzervatív első szűrő; az eredményt hasonlítsd össze a gyártó megengedett PV-teljesítmény táblázatával.</p><table><thead><tr><th>Napelem</th><th>Rendszer</th><th>Áram 25% tartalékkal</th></tr></thead><tbody><tr><td>200 Wp</td><td>12 V</td><td>21 A</td></tr><tr><td>400 Wp</td><td>12 V</td><td>42 A</td></tr><tr><td>400 Wp</td><td>24 V</td><td>21 A</td></tr></tbody></table>
<h2 id="feszultseg">2. Ellenőrizd a Voc értéket a legalacsonyabb hőmérsékleten</h2><p>Soros kapcsolásnál a panel-feszültségek összeadódnak, az üresjárati feszültség pedig hidegben nő. A hőmérséklettel korrigált összes Voc értéknek a gyártó által előírt tartalékkal a szabályozó abszolút határa alatt kell maradnia.</p><div class="note"><strong>Példa a 100/30 jelölésre:</strong> a dokumentáció 100 V maximális Voc és 30 A töltőáram határt adhat meg. Ettől még külön ellenőrizni kell az Isc értéket és a megengedett PV-teljesítményt.</div>
<h2 id="ellenorzes">3. Öt paraméternek kell egyszerre megfelelnie</h2><ol><li><strong>Akkumulátorfeszültség:</strong> 12, 24 vagy 48 V a rendszer szerint.</li><li><strong>Maximális PV Voc:</strong> a legalacsonyabb hőmérsékletre korrigálva.</li><li><strong>Rövidzárási áram, Isc:</strong> a párhuzamos ágakkal és a szükséges tartalékkal.</li><li><strong>Megengedett PV-teljesítmény:</strong> az akkumulátorfeszültségtől függően.</li><li><strong>Töltési profil:</strong> a konkrét AGM- vagy LiFePO₄-akkumulátorhoz illesztve.</li></ol>
<h2 id="pelda">Példa egy adatlapból</h2><p>A Victron SmartSolar 100/20 <a href="https://www.victronenergy.com/media/pg/Manual_SmartSolar_MPPT_75-10_up_to_100-20/en/technical-specifications.html" rel="nofollow noopener">műszaki specifikációja</a> 20 A akkumulátoráramot, 100 V maximális Voc értéket, valamint 12 V-on 290 W, 24 V-on 580 W PV-teljesítményt ad meg. Ugyanaz a szabályozó tehát magasabb akkumulátorfeszültségnél nagyobb panelteljesítményt fogadhat. Ez a szabály magyarázata, nem termékajánlás.</p>${calculatorCta("Számítsd ki az MPPT-t a teljes rendszerrel")}`,
  },
  inverter: {
    title: "Mekkora inverter kell a lakóautóba? Teljesítményszámítás",
    description: "Számítsd ki a lakóautó 12/230 V-os inverterének szükséges teljesítményét. Folyamatos terhelés, indítási csúcs, tiszta szinusz és akkumulátoráram.",
    kicker: "230 V a lakóautóban",
    heading: "Mekkora inverterre van szükséged?",
    lead: "Nem csak a wattok összege számít, hanem az egyidejű használat, az indítási terhelés és az akkumulátortól igényelt nagy egyenáram is.",
    reading: "9 perc olvasás",
    toc: [["folyamatos","Folyamatos teljesítmény"],["inditas","Indítási csúcs"],["aram","Akkumulátoráram"],["magyar-peldak","Magyar példák"],["szinusz","Szinuszhullám"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Add össze az egyszerre működő 230 V-os készülékek teljesítményét, adj legalább 20–25% tartalékot, és külön ellenőrizd az indítási csúcsteljesítményt. Egy 1000 W-os inverter nem feltétlenül elég egy 900 W-os névleges készülékhez.</div>
<h2 id="folyamatos">1. Folyamatos teljesítmény</h2><div class="formula">Minimális folyamatos teljesítmény ≈ egyidejű AC-terhelés × 1,25</div><p>Egy 90 W-os laptop és 30 W-nyi töltő együtt 120 W; az első becslés tartalékkal 150 W. Egy 1200 W-os kávéfőzőhöz jóval nagyobb inverter, megfelelő akkumulátor, BMS és vezetékezés szükséges.</p>
<h2 id="inditas">2. Indítási terhelés</h2><p>Motorok, kompresszorok és egyes tápegységek rövid ideig a névleges teljesítmény többszörösét vehetik fel. Hasonlítsd össze a fogyasztó adatát az inverter pontosan megadott csúcsteljesítményével és annak időtartamával. A „2000 W peak” két másodpercig nem jelent 2000 W-ot több percen át.</p><p>A Victron 800 VA modell hivatalos adata 25 °C-on 1200 W 15 másodpercig, miközben 40 °C-on a folyamatos teljesítmény csak 650 W. A beépítési hőmérséklet ezért lényeges.</p>
<h2 id="aram">3. Áram a DC-oldalon</h2><div class="formula">Akkumulátoráram (A) ≈ AC-teljesítmény (W) ÷ feszültség (V) ÷ hatásfok</div><p>1200 W, 12 V és 90% hatásfok mellett ez körülbelül <strong>111 A</strong>. Ezt a BMS-nek, akkumulátornak, vezetéknek, biztosítéknak, kötéseknek és leválasztónak is el kell viselnie. 24 V-on az áram nagyjából feleződik.</p><table><thead><tr><th>AC-terhelés</th><th>12 V / 90%</th><th>24 V / 90%</th></tr></thead><tbody><tr><td>300 W</td><td>≈ 28 A</td><td>≈ 14 A</td></tr><tr><td>1000 W</td><td>≈ 93 A</td><td>≈ 46 A</td></tr><tr><td>2000 W</td><td>≈ 185 A</td><td>≈ 93 A</td></tr></tbody></table>
<h2 id="magyar-peldak">Magyar használati példák</h2><div class="example"><h3>Mobil munka a Balatonnál</h3><p>Egy 90 W-os laptop, 35 W-os kijelző és 15 W-os router együtt 140 W. A 25%-os tartalékkal 175 W adódik, ezért a gyakorlati választás egy <strong>300 W-os tiszta szinuszos inverter</strong>. Az 1000 W-os modell itt nem növeli az autonómiát.</p><h3>Hajszárító egy hálózat nélküli megállón</h3><p>Egy 1200 W-os hajszárítóhoz tartalékkal 1500 W-os inverter szükséges, amely 12 V-on körülbelül 139 A-t kérhet. Ha a BMS csak 100 A-t enged, nem az inverter a szűk keresztmetszet. A legkisebb értelmes változtatás kisebb teljesítményű készülék vagy 230 V-os csatlakozás használata; önmagában egy nagyobb inverter nem oldja meg a problémát.</p></div>
<h2 id="szinusz">Tiszta vagy módosított szinusz?</h2><p>A tiszta szinuszhullám biztonságosabb kiindulópont elektronikához, motorokhoz és vegyes fogyasztókhoz. A módosított jel zajt, túlmelegedést vagy hibás működést okozhat; mindig a készülék gyártói követelménye dönt.</p><div class="note"><strong>A nagyobb inverter nem automatikusan jobb.</strong> Drágább, erősebb DC-oldalt igényel és nagyobb lehet a saját fogyasztása. A valós egyidejű terheléshez méretezd.</div>
${calculatorCta("Számítsd ki az invertert a saját készülékeidhez")}<p>A hőmérséklet és rövid idejű túlterhelés hatását a <a href="https://www.victronenergy.com/media/pg/Inverter_VE.Direct_230V_-_HW15/en/technical-specifications.html" rel="nofollow noopener">Victron Inverter VE.Direct hivatalos specifikációja</a> szemlélteti.</p>`,
  },
  dcDc: {
    title: "Hogyan válassz DC–DC töltőt lakóautóhoz?",
    description: "DC–DC töltő méretezése alternátorról: energia, menetidő, bemeneti áram, 12/24 V, LiFePO₄ vagy AGM, intelligens alternátor és kábelezés.",
    kicker: "Töltés menet közben",
    heading: "Hogyan válassz DC–DC töltőt?",
    lead: "A 30 A-es kimenet önmagában kevés adat. Számít a fogyasztás, menetidő, mindkét akkumulátor feszültsége és kémiája, az alternátor tartaléka, a bemeneti áram és a vezetékezés.",
    reading: "11 perc olvasás",
    toc: [["mikor","Mikor kell DC–DC"],["szamitas","Áramszámítás"],["magyar-ut","Magyar példa"],["akkumulator","Akkumulátor"],["feszultseg","Bemenet és kimenet"],["alternator","Alternátor"],["vezetek","Vezeték"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>Először határozd meg, mennyi energiát szeretnél egy átlagos út alatt visszatölteni. A szükséges kimeneti áramot a Wh-ban megadott energia, a menetidő, a fedélzeti akkumulátor feszültsége és a hatásfok adja. Ezután ellenőrizd mindkét feszültséget, a töltési profilt, a BMS-t, az alternátor tartalékát, a motorjárás érzékelését, hűtést, kábeleket és védelmeket.</div>
<h2 id="mikor">Mikor indokolt a DC–DC töltő?</h2><p>Leválasztja az indítóakkumulátort a fedélzetitől, szabályozott töltési profilt és áramkorlátozást biztosít. Különösen fontos LiFePO₄ akkumulátornál és változó feszültségű intelligens alternátornál. Egy egyszerű leválasztórelé nem biztosít profilt, áramkorlátot vagy 12/24 V-os átalakítást.</p>
<h2 id="szamitas">1. Számítsd ki az áramot az energiából és a menetidőből</h2><div class="formula">Kimeneti áram (A) ≈ napi Wh ÷ menetidő (h) ÷ akkumulátorfeszültség (V) ÷ 0,90</div><p>600 Wh, két óra menetidő és 12 V esetén: 600 ÷ 2 ÷ 12 ÷ 0,90 ≈ <strong>27,8 A</strong>. Az első szokásos méret, amely ezt lefedi, 30 A.</p><table><thead><tr><th>Energia</th><th>Menetidő</th><th>Rendszer</th><th>Eredmény</th></tr></thead><tbody><tr><td>300 Wh</td><td>2 h</td><td>12 V</td><td>13,9 A → 15 A</td></tr><tr><td>600 Wh</td><td>2 h</td><td>12 V</td><td>27,8 A → 30 A</td></tr><tr><td>600 Wh</td><td>2 h</td><td>24 V</td><td>13,9 A → 15 A</td></tr><tr><td>900 Wh</td><td>1 h</td><td>12 V</td><td>83,3 A → egyedi tervezés</td></tr></tbody></table><div class="note"><strong>Nem kell mindig a teljes napi fogyasztást menet közben pótolni.</strong> A többit fedezheti napelem vagy 230 V-os csatlakozás.</div>
<h2 id="magyar-ut">Rövid áthelyezés a Balaton körül</h2><div class="example"><p>500 Wh visszatöltése 1,5 óra alatt 500 ÷ 1,5 ÷ 12 ÷ 0,90 = <strong>30,9 A</strong> kimeneti áramot igényelne. Ez azonban nem automatikusan 30–35 A-es vásárlási javaslat: egy 100 Ah LiFePO₄ akkumulátor tervezési korlátja 20 A, hacsak a gyártó és a BMS többet nem enged.</p><p>Ilyenkor a helyes döntés lehet a részleges menet közbeni töltés, majd napelem vagy 230 V használata — nem az akkumulátor és az alternátor korlátjainak átlépése.</p></div>
<h2 id="akkumulator">2. Az akkumulátornak és a BMS-nek fogadnia kell az áramot</h2><p>Ellenőrizd az ajánlott és maximális töltőáramot, feszültségeket és hőmérsékleteket. A kalkulátor tervezési korlátja LiFePO₄ esetén 0,2 C, AGM-nél 0,1 C. 100 Ah esetén ez 20 A, illetve 10 A, hacsak a gyártó vagy a BMS alacsonyabbat nem ír elő.</p>
<h2 id="feszultseg">3. Ellenőrizd a bemenetet és a kimenetet</h2><p>A 12/12-30 modell 12 V-ot fogad és 12 V-os rendszert tölt legfeljebb 30 A-rel. A 12/24-15 bemenete 12 V, kimenete 24 V. Mindkét feszültségnek és a töltési profilnak is illeszkednie kell.</p><div class="formula">Bemeneti áram (A) ≈ kimeneti áram × kimeneti feszültség ÷ bemeneti feszültség ÷ 0,90</div><table><thead><tr><th>Változat</th><th>Kimeneti teljesítmény</th><th>Bemeneti áram</th></tr></thead><tbody><tr><td>12 → 12 V, 30 A</td><td>360 W</td><td>≈ 34 A</td></tr><tr><td>12 → 24 V, 15 A</td><td>360 W</td><td>≈ 34 A</td></tr><tr><td>12 → 24 V, 30 A</td><td>720 W</td><td>≈ 67 A</td></tr></tbody></table>
<h2 id="alternator">4. Ellenőrizd az alternátort és a bekapcsolást</h2><ol><li><strong>Alternátortípus:</strong> legyen kifejezett intelligensalternátor-támogatás.</li><li><strong>Tartalék:</strong> a névleges alternátoráram nem áll teljesen rendelkezésre a felépítménynek.</li><li><strong>Bekapcsolás:</strong> a támogatott motorjárás-érzékelést vagy ignition/D+ jelet használd.</li><li><strong>Indítóakkumulátor:</strong> álló motornál nem merülhet.</li><li><strong>Hőmérséklet:</strong> tartsd be a hűtési és szerelési előírásokat.</li></ol>
<h2 id="vezetek">5. A vezetéket ne a kimeneti áram alapján válaszd</h2><p>A bemeneti oldalon a gyártó maximális bemeneti áramát, a teljes áramköri hosszt, feszültségesést, terhelhetőséget, hőmérsékletet és fektetést kell figyelembe venni. A biztosíték a vezetéket védi; értéke nem határozható meg biztonságosan csak a fenti képletből.</p>
${calculatorCta("Számítsd ki a DC–DC töltőt a saját fogyasztásodhoz")}<p>A vezérelt töltés és motorjárás-érzékelés követelményeit a <a href="https://www.victronenergy.com/upload/documents/Orion-Tr_Smart_DC-DC_Charger_-_Isolated/34439-Orion-Tr_Smart_DC-DC_Charger-pdf-en.pdf" rel="nofollow noopener">Victron Orion-Tr Smart hivatalos kézikönyve</a> részletezi.</p>`,
  },
  shore: {
    title: "Hogyan válassz 230 V-os akkumulátortöltőt lakóautóhoz?",
    description: "230 V-os töltő méretezése LiFePO₄ vagy AGM akkumulátorhoz: töltőáram, idő, profil, hálózati fogyasztás, kábelezés és védelem.",
    kicker: "Töltés hálózati csatlakozásról",
    heading: "Hogyan válassz 230 V-os töltőt?",
    lead: "A megfelelő áram a visszatöltendő energiából, a rendelkezésre álló időből, a feszültségből és az akkumulátor korlátaiból következik. A „20 A” felirat önmagában nem elég.",
    reading: "10 perc olvasás",
    toc: [["szamitas","Áramszámítás"],["magyar-kemping","Magyar példa"],["akkumulator","Akkumulátor"],["profil","Profil és szerelés"],["halozat","Hálózati csatlakozás"],["telepites","Telepítés"]],
    body: `<div class="answer"><strong>Rövid válasz</strong>A kimeneti áramot becsüld meg a visszatöltendő energiából és a hálózaton töltött időből. Ezután ellenőrizd az akkumulátor feszültségét, kémiáját és profilját, a BMS korlátait, hőmérsékletet, hálózati fogyasztást, szerelési környezetet, DC-kábelt és a pontos modell előírt védelmeit.</div>
<h2 id="szamitas">1. Számítsd ki az áramot az energiából és az időből</h2><div class="formula">Kimeneti áram (A) ≈ visszatöltendő Wh ÷ idő (h) ÷ akkumulátorfeszültség (V) ÷ 0,90</div><p>600 Wh visszatöltése 8 óra alatt, 12 V-on: 600 ÷ 8 ÷ 12 ÷ 0,90 ≈ <strong>6,9 A</strong>. Az első szokásos méret 10 A.</p><table><thead><tr><th>Energia</th><th>Idő</th><th>Rendszer</th><th>Eredmény</th></tr></thead><tbody><tr><td>600 Wh</td><td>8 h</td><td>12 V</td><td>6,9 A → 10 A</td></tr><tr><td>1000 Wh</td><td>8 h</td><td>12 V</td><td>11,6 A → 15 A</td></tr><tr><td>1000 Wh</td><td>4 h</td><td>12 V</td><td>23,1 A → 25 A</td></tr><tr><td>1000 Wh</td><td>8 h</td><td>24 V</td><td>5,8 A → 10 A</td></tr></tbody></table><div class="note"><strong>A tényleges töltési idő nem egyszerű osztás.</strong> Az abszorpciós szakaszban csökken az áram, a közben működő fogyasztók pedig elviszik a teljesítmény egy részét.</div>
<h2 id="magyar-kemping">Éjszaka egy termálkempingben</h2><div class="example"><p>1 000 Wh tíz óra alatti visszatöltéséhez 1 000 ÷ 10 ÷ 12 ÷ 0,90 = <strong>9,3 A</strong> szükséges, ezért a 10 A-es töltő elméletben elegendő. Rövidebb tartózkodásnál lehet indokolt nagyobb modell, de csak az akkumulátor és a BMS határain belül.</p><p>A töltő a kemping csatlakozását a bojlerrel, fűtéssel, klímával és vízforralóval együtt használja. A maximális hálózati felvételt ezért mindig együtt kell ellenőrizni a többi fogyasztóval.</p></div>
<h2 id="akkumulator">2. Az akkumulátor és a BMS korlátja az első</h2><p>Ellenőrizd az ajánlott és maximális áramot, feszültséget és hőmérsékletet. LiFePO₄ esetén jóváhagyott profil és hidegtöltés elleni védelem szükséges. AGM-nél az abszorpciós és fenntartó feszültség helyessége fontos. A kalkulátor LiFePO₄-nél 0,2 C, AGM-nél 0,1 C tervezési limitet használ, de a gyártó alacsonyabb korlátja az irányadó.</p>
<h2 id="profil">3. Ellenőrizd a profilt, feszültséget és szerelést</h2><ol><li><strong>Feszültség:</strong> 12 V-os töltő nem illik 24 V-os akkumulátorhoz.</li><li><strong>Kémia:</strong> a konkrét töltési fázisokat és feszültségeket ellenőrizd.</li><li><strong>Szerelés:</strong> biztosítsd az előírt hűtést, helyzetet és védettséget.</li><li><strong>Fogyasztók:</strong> a kimeneti áram egy része az aktív berendezéseket táplálhatja.</li><li><strong>Kimenetek:</strong> több kimenet nem feltétlenül növeli a teljes rendelkezésre álló áramot.</li></ol>
<h2 id="halozat">4. Ellenőrizd a hálózati fogyasztást és a csatlakozás határát</h2><div class="formula">Becsült hálózati teljesítmény (W) ≈ kimeneti feszültség × kimeneti áram ÷ hatásfok</div><p>Egy 12 V/30 A töltő körülbelül 360 W-ot ad DC-oldalon; 90%-os hatásfok mellett becslés szerint 400 W-ot vesz fel. A választáshoz a gyártó maximális hálózati felvételét használd.</p><p>A kemping csatlakozását a bojler, fűtés, klíma és vízforraló is terheli. 6 A esetén az elméleti határ 230 V-on körülbelül 1380 W, de tartalékot kell hagyni.</p>
<h2 id="telepites">5. A DC-oldal és a 230 V-os védelem két külön áramkör</h2><p>A DC-kábelt a maximális kimeneti áram, teljes hossz, feszültségesés, hőmérséklet és fektetés szerint válaszd. AC-oldalon megfelelő védővezető, RCD, túláramvédelem, csatlakozás és keresztmetszet szükséges. A szerelés ismerete nélkül nincs egyetlen univerzális biztosítékérték.</p>
${calculatorCta("Számítsd ki a 230 V-os töltőt a saját rendszeredhez")}<p>A töltési profilokat és hőmérsékleti korlátokat a <a href="https://www.victronenergy.com/media/pg/Blue_Smart_IP22_Charger_230V_manual/en/quick-start-guide---bsc---psc.html" rel="nofollow noopener">Victron Blue Smart IP22 hivatalos kézikönyve</a> szemlélteti.</p>`,
  },
});

export function renderHungarianGuide(kind) {
  if (kind === "hub") return renderHub();
  const guide = guides[kind];
  if (!guide || !HU_GUIDE_ROUTES[kind]) throw new Error(`HU_GUIDE_UNKNOWN:${kind}`);
  const route = HU_GUIDE_ROUTES[kind];
  const schema = JSON.stringify({ "@context":"https://schema.org", "@type":"Article", headline:guide.heading, inLanguage:"hu-HU", author:{ "@type":"Person", name:"Petr Gálík", url:"https://mypowersetup.com/hu/a-projektrol/" }, mainEntityOfPage:`https://mypowersetup.com${route}` });
  return `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>${guide.title}</title><meta name="description" content="${guide.description}"><meta property="og:title" content="${guide.title}"><meta property="og:description" content="${guide.description}"><meta property="og:type" content="article"><meta property="og:url" content="https://mypowersetup.com${route}"><meta property="og:locale" content="hu_HU"><meta property="og:image" content="https://mypowersetup.com/social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/article.css"><script type="application/ld+json">${schema}</script></head><body>${header()}<section class="article-hero"><div class="article-hero-inner"><div class="crumbs"><a href="/hu/">Kezdőlap</a> › <a href="${HU_GUIDE_ROUTES.hub}">Útmutatók</a></div><span class="kicker">${guide.kicker}</span><h1>${guide.heading}</h1><p>${guide.lead}</p><div class="article-meta"><span>Szerző: <a href="/hu/a-projektrol/">Petr Gálík</a></span><span>Frissítve: 2026. 08. 28.</span><span>${guide.reading}</span><span>Átlátható módszertan</span></div></div></section><main class="article-layout"><article class="article">${guide.body}${safety()}</article><aside class="toc"><strong>Az útmutatóban</strong>${guide.toc.map(([id,label])=>`<a href="#${id}">${label}</a>`).join("")}</aside></main>${related(kind)}${footer()}</body></html>`;
}

function renderHub() {
  const cards = [["battery","Akkumulátorkapacitás","A napi fogyasztástól a szükséges Ah értékig."],["solar","Napelem méretezése","Évszak, veszteségek és szükséges Wp."],["mppt","MPPT kiválasztása","Áram, Voc, Isc és PV-teljesítmény együtt."],["inverter","Inverter kiválasztása","Folyamatos teljesítmény, csúcs és DC-áram."],["dcDc","DC–DC töltés","Alternátor, menetidő és biztonságos töltőáram."],["shore","230 V-os töltés","Töltési idő, profil és hálózati korlátok."]];
  return `<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Lakóautó elektromos rendszer útmutatók | MyPowerSetup</title><meta name="description" content="Gyakorlati útmutatók akkumulátor, napelem és MPPT méretezéséhez, ugyanazzal a módszertannal, amelyet a MyPowerSetup kalkulátor használ."><link rel="stylesheet" href="/article.css"></head><body>${header()}<section class="article-hero"><div class="article-hero-inner"><span class="kicker">Tudásbázis</span><h1>Érthető lakóautó-elektromosság</h1><p>A képletektől a biztonsági korlátokig: minden útmutató ugyanazt az ellenőrzött számítási modellt használja, mint a kalkulátor.</p></div></section><main class="article-layout" style="grid-template-columns:1fr"><article class="article"><div class="related-grid">${cards.map(([kind,title,text])=>`<a href="${HU_GUIDE_ROUTES[kind]}"><strong>${title}</strong><br><span>${text}</span></a>`).join("")}</div>${calculatorCta("Kezdd a saját fogyasztásoddal")}${safety()}</article></main>${footer()}</body></html>`;
}

function header() { return `<header class="article-header"><a class="article-brand" href="/hu/">⚡ MyPowerSetup</a><nav><a href="${HU_GUIDE_ROUTES.hub}">Útmutatók</a><a href="/hu/#kalkulator">Kalkulátor</a></nav></header>`; }
function calculatorCta(title) { return `<section class="cta"><h2>${title}</h2><p>Válaszd ki a fogyasztókat, az üzemidőt, az évszakot és a kívánt autonómiát.</p><a href="/hu/#kalkulator">Saját rendszer kiszámítása →</a></section>`; }
function safety() { return `<div class="sources"><h2>Források, módszertan és biztonság</h2><p>A képletek a <a href="/hu/modszertan/">nyilvános módszertanban</a> szereplő konzervatív tervezési feltételeket követik. A termékadatlap és a gyártói kézikönyv mindig elsőbbséget élvez. Az eredmény tájékoztató méretezés, nem villamos terv; a vezetékezést, védelmeket és szerelést megfelelő képesítésű szakembernek kell ellenőriznie.</p></div>`; }
function related(kind) { const map = { battery:[["solar","Napelem méretezése"]], solar:[["mppt","MPPT kiválasztása"],["battery","Akkumulátorkapacitás"]], mppt:[["solar","Napelem méretezése"],["battery","Akkumulátorkapacitás"]], inverter:[["battery","Akkumulátorkapacitás"],["dcDc","DC–DC töltés"]], dcDc:[["shore","230 V-os töltés"],["battery","Akkumulátorkapacitás"]], shore:[["dcDc","DC–DC töltés"],["battery","Akkumulátorkapacitás"]] }; const links = map[kind] || [["battery","Akkumulátorkapacitás"]]; return `<section class="related"><h2>Olvass tovább</h2><div class="related-grid">${links.map(([target,label])=>`<a href="${HU_GUIDE_ROUTES[target]}">${label} →</a>`).join("")}</div></section>`; }
function footer() { return `<footer class="article-footer">A számítás tájékoztató jellegű, nem villamos terv. A konkrét telepítést és védelmeket szakemberrel ellenőriztesd.</footer><script type="module" src="/src/analytics.js"></script>`; }
