export const HU_TRUST_COPY = Object.freeze({
  about: {
    metaTitle: "A MyPowerSetup projektről és Petr Gálík szerzőről",
    metaDescription: "Miért hozta létre Petr Gálík a MyPowerSetupot, milyen forrásokra épülnek a számítások, és hogyan választjuk el a műszaki megfelelést a partneri jutaléktól.",
    kicker: "A projektről",
    title: "Energia találgatás nélkül",
    lead: "A MyPowerSetup a fogyasztók listájából és az utazási szokásokból érthető, tájékoztató villamosrendszer-javaslatot készít.",
    principle: "Először a számítás és a műszaki megfelelés, csak utána a termék. A partneri jutalék nem döntheti el, hogy egy alkatrész megfelelő-e.",
    author: "Petr Gálík vagyok, elektrotechnikai végzettséggel rendelkezem, és magam is lakókocsit használok. A kalkulátort azért készítettem, hogy a valós fogyasztástól rövid, átlátható út vezessen a szükséges alkatrész-paraméterekhez.",
    sources: "Elsődlegesen gyártói kézikönyveket, adatlapokat és szakmai forrásokat használunk. A dokumentált adatokat elkülönítjük a tervezési feltételezésektől, a bizonytalanságokat pedig feltüntetjük.",
    limit: "Az eredmény nem villamos terv, felülvizsgálat vagy a konkrét szerelés biztonságának igazolása.",
  },
  methodology: {
    metaTitle: "Számítási és ajánlási módszertan | MyPowerSetup",
    metaDescription: "A MyPowerSetup átlátható képletei, tervezési tartalékai, biztonsági korlátai és termékillesztési szabályai.",
    kicker: "Átlátható módszertan",
    title: "Így számol a MyPowerSetup",
    version: "Módszertan: 1.4 · 2026. augusztus 28.",
    deterministic: "A számítás determinisztikus: azonos bemenethez azonos eredmény tartozik. Nem használunk generatív mesterséges intelligenciát vagy rejtett termékpreferenciát.",
    formulas: {
      consumption: "Wh/nap = teljesítmény × üzemidő × darabszám összege",
      battery: "akkumulátor Wh = napi Wh × autonóm napok × 1,15 ÷ használható kisütési mélység",
      solar: "Wp = napi Wh × 1,15 ÷ teljes napsütéses órák ÷ 0,75",
      cable: "mm² = 2 × egyirányú hossz × áram × réz fajlagos ellenállása ÷ megengedett feszültségesés",
    },
    productRules: [
      "A terméknek a megfelelő kategóriába kell tartoznia.",
      "A szükséges kulcsparamétereknek felismerhetőnek kell lenniük.",
      "A nem megfelelő feszültség vagy elégtelen teljesítmény kizáró ok.",
      "Csak a műszakilag megfelelő jelöltek között értékeljük a paraméterek közelségét, az elérhetőséget és az adatok teljességét.",
      "Egy termékoldalról csak a legmegfelelőbb változatot jelenítjük meg.",
    ],
    commission: "A jutalék nem része a pontozásnak. Az eladó és a partneri jutalék mértéke nem változtatja meg a műszaki feltételeket vagy a jelöltek sorrendjét.",
    limitation: "Az automatikusan feldolgozott paraméterek hiányosak vagy hibásak lehetnek. Vásárlás és szerelés előtt mindig ellenőrizni kell a gyártó aktuális dokumentációját és a teljes rendszer követelményeit.",
  },
  affiliate: {
    metaTitle: "Partnerlinkek és ajánlási függetlenség | MyPowerSetup",
    title: "Hogyan finanszírozzuk a projektet",
    disclosure: "Egyes termékhivatkozások partnerlinkek. Ha ezeken keresztül vásárolsz, jutalékot kaphatunk anélkül, hogy neked többe kerülne.",
    independence: "A jutalék nem befolyásolja, hogy egy termék megfelel-e a számított rendszernek, és nem írhatja felül a műszaki sorrendet.",
    verification: "Az árat, készletet, szállítást, garanciát és a pontos műszaki adatokat a kereskedő vagy a gyártó oldalán kell ellenőrizni.",
    choice: "A kalkulátor ingyenesen, regisztráció és vásárlás nélkül is használható.",
  },
  privacy: {
    metaTitle: "Adatvédelem és műszaki adatok | MyPowerSetup",
    metaDescription: "Hogyan kezeli a MyPowerSetup a kalkulátor adatait, a külső termékképeket, a partnerlinkeket és az analitikai hozzájárulást.",
    kicker: "Adatvédelem",
    title: "Mi történik az adataiddal?",
    localProcessing: "A kiválasztott fogyasztókat, üzemidőket és más bemeneteket a böngésződben futó JavaScript dolgozza fel. A kalkulátorhoz nem kell fiók, név vagy e-mail-cím.",
    analytics: "A Google Analytics 4 csak kifejezett hozzájárulás után indul el. A hozzájárulás megtagadása nem korlátozza a kalkulátor használatát.",
    outgoing: "A termékajánlások megjelenítésekor a böngésző külső kereskedői domainről tölthet be képeket. Partnerlinkre kattintva a kérés partnerhálózaton keresztül juthat el a kereskedőhöz.",
    consentKey: "mypowersetup_analytics_consent",
    contact: "xfit.redakce@gmail.com",
  },
  safety: {
    title: "Biztonsági határ",
    text: "A MyPowerSetup tájékoztató méretezőeszköz. A kábeleket, biztosítékokat, leválasztást, BMS-t, töltési profilokat, hőmérsékleti feltételeket és a szerelést megfelelő képesítésű szakembernek kell ellenőriznie.",
  },
});
