export const RO_UI_COPY = Object.freeze({
  meta: {
    title: "Calculator baterie și panouri solare pentru autorulotă | MyPowerSetup",
    description: "Calculează capacitatea bateriei, puterea panourilor solare, invertorul și controlerul MPPT necesare pentru autorulotă, cu fiecare rezultat explicat.",
  },
  navigation: {
    guides: "Ghiduri",
    method: "Cum calculăm",
    calculator: "Calculator",
  },
  hero: {
    eyebrow: "Energie fără estimări la întâmplare",
    title: "De câtă baterie și energie solară ai nevoie cu adevărat?",
    lead: "Alege consumatorii. În câteva minute primești o recomandare explicată pentru baterie, panouri solare, invertor și controler MPPT.",
    noRegistration: "Fără înregistrare",
    transparent: "Calcule transparente",
    free: "Gratuit",
    action: "Calculează sistemul meu",
  },
  calculator: {
    title: "Trei pași până la sistemul tău de energie",
    intro: "Poți modifica valorile după datele reale de pe eticheta fiecărui aparat.",
    steps: ["Utilizare", "Consumatori", "Rezultat"],
    usageTitle: "Când și cum vei folosi energia?",
    usageIntro: "Folosim aceste informații pentru rezerva bateriei și dimensionarea panourilor solare.",
    autonomy: "Câte zile vrei să funcționezi fără reîncărcare?",
    season: "În ce perioadă a anului trebuie să funcționeze sistemul?",
    appliancesTitle: "Ce vrei să alimentezi în fiecare zi?",
    appliancesIntro: "Selectează consumatorii și ajustează durata de utilizare. Valorile inițiale sunt estimări tipice, nu date garantate.",
    selected: "Consumatori selectați",
    dailyEstimate: "Consum zilnic estimat",
    selectAtLeastOne: "Selectează cel puțin un consumator.",
    advanced: "Setări avansate ale sistemului",
    calculate: "Calculează sistemul",
    back: "Înapoi",
  },
  advanced: {
    batteryType: "Tipul bateriei",
    voltage: "Tensiunea sistemului",
    automatic: "Alegere automată",
    inverterCable: "Lungimea cablului baterie–invertor, într-un singur sens",
    driveHours: "Timp obișnuit de condus pe zi",
    starterVoltage: "Tensiunea sistemului de pornire",
    dcDcCable: "Lungimea cablului baterie de pornire–încărcător DC-DC, într-un singur sens",
    shoreHours: "Durata conectării la 230 V",
    roofLength: "Lungimea zonei libere dreptunghiulare de pe acoperiș",
    roofWidth: "Lățimea zonei libere dreptunghiulare de pe acoperiș",
    optional: "Opțional",
  },
  result: {
    kicker: "Recomandare orientativă de sistem",
    title: "Sistem dimensionat cu rezervă",
    battery: "Baterie",
    solar: "Panouri solare",
    inverter: "Invertor cu undă sinusoidală pură",
    inverterNotNeeded: "Nu este necesar",
    controller: "Controler MPPT",
    next: "Pasul următor",
    compatibleComponents: "Alege componente compatibile",
    showProducts: "Vezi produsele recomandate ↓",
    save: "Salvează rezultatul",
    shareTitle: "Salvează sau distribuie recomandarea",
    share: "Distribuie rezultatul",
    copy: "Copiază rezumatul",
    print: "Tipărește / salvează ca PDF",
    why: "Cum am ajuns la aceste valori?",
    consumption: "De unde vine consumul de energie?",
    preflight: "Verificări înainte de instalare",
    diagram: "Schemă orientativă a sistemului",
    charging: "Încărcare în mers și de la 230 V",
    roof: "Încap panourile pe acoperiș?",
    installation: "Circuite care trebuie proiectate și verificate de un specialist calificat",
    powerStationComparison: "Sistem fix sau stație de energie portabilă?",
    change: "Modifică consumatorii",
    restart: "Începe din nou",
  },
  products: {
    verifiedMatch: "Compatibilitate verificată",
    heading: "Componente compatibile cu rezultatul calculului",
    intro: "Verificăm mai întâi compatibilitatea tehnică. Abia apoi ordonăm opțiunile după potrivirea parametrilor, disponibilitate și calitatea datelor.",
    preparing: "Pregătim recomandări exacte de produse",
    exactProduct: "Vezi produsul exact →",
    storePrice: "Preț în magazin",
    categories: {
      battery: "Baterii",
      solarPanel: "Panouri solare",
      inverter: "Invertoare",
      controller: "Controlere MPPT",
      dcCharger: "Încărcătoare DC-DC pentru mers",
      shoreCharger: "Încărcătoare de rețea 230 V",
      powerStation: "Stații de energie portabile",
    },
    packages: {
      heading: "Trei variante de cumpărare în siguranță",
      economy: "Economică",
      recommended: "Recomandată",
      reserve: "Cu rezervă mai mare",
      priceNote: "Total orientativ al produselor, fără transport și instalare.",
    },
    affiliate: "Unele linkuri pot fi linkuri de afiliere. Comisionul nu schimbă criteriile tehnice sau ordinea recomandărilor.",
  },
  method: {
    title: "Fiecare rezultat poate fi explicat",
    consumption: "Calculăm consumul",
    losses: "Adăugăm pierderile reale",
    surge: "Verificăm vârfurile de putere la pornire",
  },
  safety: {
    title: "Înainte să cumperi",
    text: "Calculatorul oferă o dimensionare orientativă, nu un proiect electric. Datele nominale, cablurile, protecțiile, separarea circuitelor și condițiile de instalare trebuie verificate de un specialist calificat.",
  },
  footer: {
    about: "Despre proiect și autor",
    methodology: "Metodologie",
    affiliate: "Afiliere",
    privacy: "Confidențialitate",
  },
});
