export const HU_UI_COPY = Object.freeze({
  meta: {
    title: "Lakóautó akkumulátor- és napelem-kalkulátor | MyPowerSetup",
    description: "Számítsd ki a lakóautóhoz szükséges akkumulátorkapacitást, napelemteljesítményt, invertert és MPPT töltésvezérlőt. Ingyenesen, minden eredmény magyarázatával.",
  },
  navigation: {
    guides: "Útmutatók",
    method: "Így számolunk",
    calculator: "Kalkulátor",
  },
  hero: {
    eyebrow: "Energia találgatás nélkül",
    title: "Mekkora akkumulátorra és napelemre van valóban szükséged?",
    lead: "Válaszd ki a fogyasztókat. Két perc alatt érthető javaslatot kapsz az akkumulátorra, a napelemekre, az inverterre és az MPPT töltésvezérlőre — indoklással együtt.",
    noRegistration: "Regisztráció nélkül",
    transparent: "Átlátható számítások",
    free: "Ingyenes",
    action: "A rendszerem kiszámítása",
  },
  calculator: {
    title: "Három lépés a saját energiaellátásodhoz",
    intro: "Az értékeket a készülékek adattáblája alapján módosíthatod.",
    steps: ["Használat", "Fogyasztók", "Eredmény"],
    usageTitle: "Mikor és hogyan használod majd az energiát?",
    usageIntro: "Ez alapján választjuk ki a tartalékot és a napelemek teljesítményét.",
    autonomy: "Hány napig szeretnél töltés nélkül működni?",
    season: "Melyik időszakban kell működnie a rendszernek?",
    appliancesTitle: "Mit szeretnél naponta működtetni?",
    appliancesIntro: "Válaszd ki a fogyasztókat, majd módosítsd az üzemidőt. A kezdőértékek tipikus becslések.",
    selected: "Kiválasztott fogyasztók",
    dailyEstimate: "Becsült napi fogyasztás",
    selectAtLeastOne: "Válassz legalább egy fogyasztót.",
    advanced: "A rendszer speciális beállításai",
    calculate: "Rendszer kiszámítása",
    back: "Vissza",
  },
  advanced: {
    batteryType: "Akkumulátor típusa",
    voltage: "Rendszerfeszültség",
    automatic: "Automatikus választás",
    inverterCable: "Akkumulátor–inverter kábelhossz egy irányban",
    driveHours: "Tipikus napi vezetési idő",
    starterVoltage: "Indítórendszer feszültsége",
    dcDcCable: "Indítóakkumulátor–DC–DC kábelhossz egy irányban",
    shoreHours: "230 V-os csatlakozás időtartama",
    roofLength: "A tető szabad téglalapjának hossza",
    roofWidth: "A tető szabad téglalapjának szélessége",
    optional: "Nem kötelező",
  },
  result: {
    kicker: "Tájékoztató rendszerjavaslat",
    title: "Rendszer biztonsági tartalékkal",
    battery: "Akkumulátor",
    solar: "Napelemek",
    inverter: "Tiszta szinuszos inverter",
    inverterNotNeeded: "Nem szükséges",
    controller: "MPPT töltésvezérlő",
    next: "Következő lépés",
    compatibleComponents: "Válassz kompatibilis alkatrészeket",
    showProducts: "Ajánlott termékek megjelenítése ↓",
    save: "Eredmény mentése",
    shareTitle: "Mentsd el vagy oszd meg a rendszerjavaslatot",
    share: "Eredmény megosztása",
    copy: "Összefoglaló másolása",
    print: "Nyomtatás / mentés PDF-ként",
    why: "Hogyan kaptuk ezeket az értékeket?",
    consumption: "Mi adja az energiafogyasztást?",
    preflight: "Ellenőrzés a kivitelezés előtt",
    diagram: "Tájékoztató rendszerkapcsolás",
    charging: "Töltés menet közben és 230 V-ról",
    roof: "Elférnek a napelemek a tetőn?",
    installation: "Az áramkörök, amelyeket szakembernek kell megterveznie és ellenőriznie",
    powerStationComparison: "Fix rendszer vagy hordozható áramforrás?",
    change: "Fogyasztók módosítása",
    restart: "Újrakezdés",
  },
  products: {
    verifiedMatch: "Ellenőrzött megfelelés",
    heading: "A számítással kompatibilis alkatrészek",
    intro: "Először a műszaki megfelelést ellenőrizzük. A sorrend ezután a paraméterek illeszkedését, az elérhetőséget és az adatok teljességét veszi figyelembe.",
    preparing: "Pontos termékajánlások előkészítése",
    exactProduct: "A pontos termék megjelenítése →",
    storePrice: "Ár a webáruházban",
    categories: {
      battery: "Akkumulátorok",
      solarPanel: "Napelemek",
      inverter: "Inverterek",
      controller: "MPPT töltésvezérlők",
      dcCharger: "Menet közbeni DC–DC akkumulátortöltők",
      shoreCharger: "230 V-os hálózati töltők",
      powerStation: "Hordozható áramforrások",
    },
    packages: {
      heading: "Három biztonságos vásárlási út",
      economy: "Takarékos",
      recommended: "Ajánlott",
      reserve: "Nagyobb tartalékkal",
      priceNote: "A termékek tájékoztató összege; szállítás és szerelés nélkül.",
    },
    affiliate: "Egyes hivatkozások partnerlinkek lehetnek. A jutalék nem módosítja a műszaki feltételeket vagy a találatok sorrendjét.",
  },
  method: {
    title: "Minden eredményt meg tudunk magyarázni",
    consumption: "Kiszámítjuk a fogyasztást",
    losses: "Hozzáadjuk a valós veszteségeket",
    surge: "Ellenőrizzük az indítási teljesítménycsúcsokat",
  },
  safety: {
    title: "Mielőtt vásárolni kezdesz",
    text: "A kalkulátor tájékoztató méretezést ad, nem villamos tervet. A névleges adatokat, kábeleket, védelmeket, leválasztást és telepítési feltételeket ellenőriztesd megfelelő képesítésű szakemberrel.",
  },
  footer: {
    about: "A projektről és a szerzőről",
    methodology: "Módszertan",
    affiliate: "Partnerkapcsolatok",
    privacy: "Adatvédelem",
  },
});
