export const PT_UI_COPY = Object.freeze({
  meta: {
    title: "Calculadora de bateria e painéis solares para autocaravana | MyPowerSetup",
    description: "Calcula a capacidade da bateria, a potência solar, o inversor e o controlador MPPT necessários para a tua autocaravana, com cada resultado explicado.",
  },
  navigation: {
    guides: "Guias",
    method: "Como calculamos",
    calculator: "Calculadora",
  },
  hero: {
    eyebrow: "Energia sem adivinhações",
    title: "De quanta bateria e energia solar precisas realmente?",
    lead: "Escolhe os consumos. Em poucos minutos recebes uma recomendação explicada para bateria, painéis solares, inversor e controlador MPPT.",
    noRegistration: "Sem registo",
    transparent: "Cálculos transparentes",
    free: "Gratuito",
    action: "Calcular o meu sistema",
  },
  calculator: {
    title: "Três passos até ao teu sistema de energia",
    intro: "Podes ajustar os valores usando os dados reais da etiqueta de cada aparelho.",
    steps: ["Utilização", "Consumos", "Resultado"],
    usageTitle: "Quando e como vais usar a energia?",
    usageIntro: "Usamos estas respostas para definir a reserva da bateria e dimensionar a potência solar.",
    autonomy: "Quantos dias queres funcionar sem recarregar?",
    season: "Em que época do ano o sistema tem de funcionar?",
    appliancesTitle: "O que queres alimentar todos os dias?",
    appliancesIntro: "Seleciona os consumos e ajusta o tempo de utilização. Os valores iniciais são estimativas típicas, não dados garantidos.",
    selected: "Consumos selecionados",
    dailyEstimate: "Consumo diário estimado",
    selectAtLeastOne: "Seleciona pelo menos um consumo.",
    advanced: "Definições avançadas do sistema",
    calculate: "Calcular sistema",
    back: "Voltar",
  },
  advanced: {
    batteryType: "Tipo de bateria",
    voltage: "Tensão do sistema",
    automatic: "Seleção automática",
    inverterCable: "Comprimento do cabo bateria–inversor, num só sentido",
    driveHours: "Tempo típico de condução por dia",
    starterVoltage: "Tensão do sistema de arranque",
    dcDcCable: "Comprimento do cabo bateria de arranque–carregador DC-DC, num só sentido",
    shoreHours: "Tempo de ligação a 230 V",
    roofLength: "Comprimento da área retangular livre no tejadilho",
    roofWidth: "Largura da área retangular livre no tejadilho",
    optional: "Opcional",
  },
  result: {
    kicker: "Recomendação indicativa de sistema",
    title: "Sistema dimensionado com margem",
    battery: "Bateria",
    solar: "Painéis solares",
    inverter: "Inversor de onda sinusoidal pura",
    inverterNotNeeded: "Não é necessário",
    controller: "Controlador MPPT",
    next: "Próximo passo",
    compatibleComponents: "Escolhe componentes compatíveis",
    showProducts: "Ver produtos recomendados ↓",
    save: "Guardar resultado",
    shareTitle: "Guarda ou partilha a recomendação",
    share: "Partilhar resultado",
    copy: "Copiar resumo",
    print: "Imprimir / guardar como PDF",
    why: "Como chegámos a estes valores?",
    consumption: "De onde vem o consumo de energia?",
    preflight: "Verificações antes da instalação",
    diagram: "Esquema indicativo do sistema",
    charging: "Carregamento em andamento e a 230 V",
    roof: "Os painéis cabem no tejadilho?",
    installation: "Circuitos que devem ser dimensionados e verificados por um técnico qualificado",
    powerStationComparison: "Sistema fixo ou estação de energia portátil?",
    change: "Alterar consumos",
    restart: "Recomeçar",
  },
  products: {
    verifiedMatch: "Compatibilidade verificada",
    heading: "Componentes compatíveis com o resultado do cálculo",
    intro: "Primeiro verificamos a compatibilidade técnica. Só depois ordenamos as opções pelo ajuste dos parâmetros, disponibilidade e qualidade dos dados.",
    preparing: "A preparar recomendações exatas de produtos",
    exactProduct: "Ver o produto exato →",
    storePrice: "Preço na loja",
    categories: {
      battery: "Baterias",
      solarPanel: "Painéis solares",
      inverter: "Inversores",
      controller: "Controladores MPPT",
      dcCharger: "Carregadores DC-DC em andamento",
      shoreCharger: "Carregadores de rede 230 V",
      powerStation: "Estações de energia portáteis",
    },
    packages: {
      heading: "Três caminhos de compra seguros",
      economy: "Económico",
      recommended: "Recomendado",
      reserve: "Com maior margem",
      priceNote: "Total indicativo dos produtos, sem transporte nem instalação.",
    },
    affiliate: "Algumas ligações podem ser links de afiliado. A comissão não altera os critérios técnicos nem a ordem das recomendações.",
  },
  method: {
    title: "Conseguimos explicar cada resultado",
    consumption: "Calculamos o consumo",
    losses: "Acrescentamos perdas realistas",
    surge: "Verificamos picos de potência no arranque",
  },
  safety: {
    title: "Antes de comprares",
    text: "A calculadora fornece um dimensionamento indicativo, não um projeto elétrico. Dados nominais, cabos, proteções, isolamento e condições de instalação devem ser verificados por um técnico qualificado.",
  },
  footer: {
    about: "Sobre o projeto e o autor",
    methodology: "Metodologia",
    affiliate: "Afiliados",
    privacy: "Privacidade",
  },
});
